package jp.seikeidenron.androidtv.model;

import android.graphics.Bitmap;
import android.os.Parcel;
import android.os.Parcelable;

import jp.seikeidenron.androidtv.common.MLog;

/**
 * ImageInfo class contains title, description, image thumbs which are shown in each card
 */
public class ImageInfo implements Parcelable {

    /*-----------------------------------------------------*/
    // Constant
    /*-----------------------------------------------------*/
    private static final String TAG = ImageInfo.class.getSimpleName();

    /*-----------------------------------------------------*/
    // Relation
    /*-----------------------------------------------------*/
    private static long count = 0;
    private int id;
    private String title;
    //private int resourceId;
    private Bitmap image;
    private String studio; // studio is used to store absolute path of image!!

    /*-----------------------------------------------------*/
    // Attribute
    /*-----------------------------------------------------*/

    /*-----------------------------------------------------*/
    // Getter/Setter
    /*-----------------------------------------------------*/
    public static long getCount() {
        return count;
    }

    public static void incCount() {
        count++;
    }

    public int getId() {
        return id;
    }

    public void setId(int id) {
        this.id = id;
    }

    public String getTitle() {
        if (title == null) {
            MLog.w(TAG, "title is null!");
            return "";
        }

        return title;
    }

    public void setTitle(String title) {
        this.title = title;
    }

    public String getStudio() {
        if (studio == null) {
            MLog.w(TAG, "studio is null!");
            return "";
        }

        return studio;
    }

    public void setStudio(String studio) {
        this.studio = studio;
    }

    public Bitmap getImage() {
        return image;
    }

    public void setImage(Bitmap image) {
        this.image = image;
    }

    /*-----------------------------------------------------*/
    // Ctor
    /*-----------------------------------------------------*/
    public ImageInfo() {

    }

    public ImageInfo(int id, String title, String studio, Bitmap image) {
        this.id = id;
        this.title = title;
        this.studio = studio;
        this.image = image;
    }

    /*-----------------------------------------------------*/
    //	Override/Implementation
    /*-----------------------------------------------------*/
    @Override
    public String toString() {
        return "cardInfo{" +
                "id=" + id +
                ", title='" + title + '\'' +
                ", image='" + image.toString() + '\'' +
                ", studio='" + studio + '\'' +
                '}';
    }

    /*-----------------------------------------------------*/
    //	Public method
    /*-----------------------------------------------------*/

    /*-----------------------------------------------------*/
    //	Protected method
    /*-----------------------------------------------------*/

    /*-----------------------------------------------------*/
    //	Private method
    /*-----------------------------------------------------*/

    /*-----------------------------------------------------*/
    //	Inner class
    /*-----------------------------------------------------*/

    /* Autogenerated Parcelable methods. */

    @Override
    public int describeContents() {
        return 0;
    }

    @Override
    public void writeToParcel(Parcel dest, int flags) {
        dest.writeInt(this.id);
        dest.writeString(this.title);
        dest.writeParcelable(this.image, 0);
        dest.writeString(this.studio);
    }

    protected ImageInfo(Parcel in) {
        this.id = in.readInt();
        this.title = in.readString();
        this.image = in.readParcelable(Bitmap.class.getClassLoader());
        this.studio = in.readString();
    }

    public static final Creator<ImageInfo> CREATOR = new Creator<ImageInfo>() {
        public ImageInfo createFromParcel(Parcel source) {
            return new ImageInfo(source);
        }

        public ImageInfo[] newArray(int size) {
            return new ImageInfo[size];
        }
    };
}